version: '3.9'

services:
  master:
    image: redis:latest
    container_name: redis-master
    ports:
      - '6379:6379'

  slave:
    image: redis:latest
    container_name: redis-slave
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - master
    ports:
      - '6380:6379'

  sentinel:
    build:
      context: ./sentinel
      dockerfile: Dockerfile
    container_name: redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    ports:
      - '26379:26379'
    depends_on:
      - master
      - slave
